<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-24CC5IF" failures="1" tests="7" name="Checkout_process.createNewAccountTest" time="81.082" errors="0" timestamp="2023-04-01T18:27:05 EET" skipped="0">
  <testcase classname="Checkout_process.createNewAccountTest" name="createNewAccountWithValidAccount" time="11.424"/>
  <system-out/>
  <testcase classname="Checkout_process.createNewAccountTest" name="createNewAccountWithEmptyName" time="7.976"/>
  <system-out/>
  <testcase classname="Checkout_process.createNewAccountTest" name="createNewAccountWithEmpteyPassword" time="9.130">
    <failure message="expected [This field is required] but found [This field is required.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [This field is required] but found [This field is required.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.crm.qa.pages.createNewAccountPage.assertFalidRegistration(createNewAccountPage.java:66)
at Checkout_process.createNewAccountTest.createNewAccountWithEmpteyPassword(createNewAccountTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createNewAccountWithEmpteyPassword -->
  <system-out/>
  <testcase classname="Checkout_process.createNewAccountTest" name="createNewAccountWithUnmatchedPassword" time="16.434"/>
  <system-out/>
  <testcase classname="Checkout_process.createNewAccountTest" name="createNewAccountWithEmptyMail" time="6.935"/>
  <system-out/>
  <testcase classname="Checkout_process.createNewAccountTest" name="createNewAccountWithPasswordLessThanMinChar" time="20.989"/>
  <system-out/>
  <testcase classname="Checkout_process.createNewAccountTest" name="createNewAccountWithEmptyLastName" time="8.194"/>
  <system-out/>
</testsuite> <!-- Checkout_process.createNewAccountTest -->
